### ISSUE TITLE
cem-plugin-readonly: logs, many logs...

### ISSUE THREAD

**Issue by hsablonniere** [bennypowers/cem-plugins#2]
Hey @bennypowers :wink:

The readonly plugin work great in my context.
I compared the CEM, one with my plugin, one with yours and the diff is null.
This is a success.

The only "problem" is I'm getting a lot of logs like this:

```
Could not find class updated
Could not find class name
Could not find class name
Could not find class define
Could not find class getText
Could not find class _getTextParts
Could not find class includes
Could not find class title
Could not find class title
Could not find class code
Could not find class name
Could not find class find
Could not find class map
Could not find class define
```

It seems to come from `getClassMemberDoc` in `manifest-helpers`.

Is it normal?

**Comment by bennypowers** [comment]
I don't even know what normal is anymore 🤣 

Yeah I think we could get rid of those logs
