### ISSUE TITLE
Support ^0.6 versions of @custom-elements-manifest/analyzer 

### ISSUE THREAD

**Issue by ddegan** [bennypowers/cem-plugins#8]
Hi! 
I'd like do use the `cem-plugin-module-file-extensions` plugin with the latest version of `@custom-elements-manifest/analyzer `. Would you mind adding the support for the **^0.6** versions?

Thanks 

Dan

**Comment by bennypowers** [comment]
I'm not planning to work on this unless cem/a implements typescript
wait for lit-labs/analyzer, or at some point i might fork in `@patternfly/pfe-tools`
